remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: HabiTech
description: A workshop at CHI2024 to help define a new research area - the building-level counterpoint to digital civics.
